name: Go Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install gotestsum and Run Tests
        run: |
          go install gotest.tools/gotestsum@latest && \
          mkdir -p test-results && \
          gotestsum --junitfile test-results/test-report.xml
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
