name: Go Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install gotestsum and Run Tests
        run: |
          go install gotest.tools/gotestsum@latest
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p test-results
          gotestsum --junitfile test-results/test-report.xml

      - name: Print Test Results XML
        run: cat test-results/test-report.xml

      # - name: Publish Test Results to CloudBees
      #   uses: cloudbees-io/publish-test-results@v1
      #   with:
      #     test-type: go
      #     path: test-results/test-report.xml

